### ISSUE TITLE
🔮 ldoc-custom binary origin

### ISSUE THREAD

**Issue by metaory** [sontungexpt/ldoc-css-styles#1]
I don't see the source for this binary 
[ldoc-custom](https://github.com/sontungexpt/ldoc-css-styles/blob/72c5b12426590433857be2b0bf6c69ddfed22e7b/ldoc-custom)

How did this came to be? 

What is it exactly?!

**Comment by sontungexpt** [comment]
https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts%2Fstilux%2Fusers%2Frecord

**Comment by sontungexpt** [comment]
This is the origin of those scripts. My bad, open source should show everything. It's just an 'ldoc' wrapper with some scripts that help you replace the CSS file and add a little JS to the HTML file to fix 'the a tag with name properties not working already'. I really don't know why??

**Comment by metaory** [comment]
> This is the origin of those scripts. My bad, open source should show everything. It's just an 'ldoc' wrapper with some scripts that help you replace the CSS file and add a little JS to the HTML file to fix 'the a tag with name properties not working already'.

Great, thanks for your prompt reply, yes I'm sure you can imagine how bad it looks to put a binary with no indication of how it was built, I suggest to include in the same repo to avoid confusions? I'm sure I wasn't the only one who saw this and avoided your solution, I'm just the first who report it. 

Thanks again :pray:

**Comment by metaory** [comment]
> https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts%2Fstilux%2Fusers%2Frecord

umm I still cant figure how this produced a binary..

for a wrapper as you describe I expected something like this;

```bash
#!/bin/bash

echo doing_stuff_stuff
echo more_stuff..

ldoc $@
```

wont be a binary, 

am I missing something?

**Comment by sontungexpt** [comment]
ah sorry, This is the origin
https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts/stilux/users/ldoc-custom
I used phone to answer you so i had mistake

**Comment by sontungexpt** [comment]
> > https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts%2Fstilux%2Fusers%2Frecord
> 
> umm I still cant figure how this produced a binary..
> 
> for a wrapper as you describe I expected something like this;
> 
> ```shell
> #!/bin/bash
> 
> echo doing_stuff_stuff
> echo more_stuff..
> 
> ldoc $@
> ```
> 
> wont be a binary,
> 
> am I missing something?

ah sorry, This is the origin
https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts/stilux/users/ldoc-custom
I used phone to answer you so i had mistake

**Comment by metaory** [comment]
> > > https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts%2Fstilux%2Fusers%2Frecord
> > 
> > 
> > umm I still cant figure how this produced a binary..
> > for a wrapper as you describe I expected something like this;
> > ```shell
> > #!/bin/bash
> > 
> > echo doing_stuff_stuff
> > echo more_stuff..
> > 
> > ldoc $@
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > wont be a binary,
> > am I missing something?
> 
> ah sorry, This is the origin https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts/stilux/users/ldoc-custom I used phone to answer you so i had mistake

no worries, thanks, but that still wont be a binary right?

```sh
$ file ldoc-custom

ldoc-custom: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d13794c3e9e3393d0508bf4be6ef846e780a7185, for GNU/Linux 4.4.0, stripped
```

**Comment by metaory** [comment]
> > > https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts%2Fstilux%2Fusers%2Frecord
> > 
> > 
> > umm I still cant figure how this produced a binary..
> > for a wrapper as you describe I expected something like this;
> > ```shell
> > #!/bin/bash
> > 
> > echo doing_stuff_stuff
> > echo more_stuff..
> > 
> > ldoc $@
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > wont be a binary,
> > am I missing something?
> 
> ah sorry, This is the origin https://github.com/sontungexpt/stilux-dotfiles/blob/v5-new/scripts/stilux/users/ldoc-custom I used phone to answer you so i had mistake

no worries, thanks, but that still wont be a binary right?

```sh
$ file ldoc-custom

ldoc-custom: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d13794c3e9e3393d0508bf4be6ef846e780a7185, for GNU/Linux 4.4.0, stripped
```

the file you linked is;

```sh
$ file scripts/stilux/users/ldoc-custom

scripts/stilux/users/ldoc-custom: Bourne-Again shell script, Unicode text, UTF-8 text executable
```

**Comment by sontungexpt** [comment]
I updated ldoc-custom new. May be this is not good. I wrote it quite a while ago.

**Comment by metaory** [comment]
> I updated ldoc-custom new. May be this is not good. I wrote it quite a while ago.

I see you replaced the binary on 6290da2

Now I cant stop wondering what it was all the while before your commit! :sweat_smile:
